services:
  frontend:
    container_name: obsidian-theme
    image: ghcr.io/xsneaco/obsidian-theme-creator/frontend:${IMAGE_TAG:-latest}
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    networks:
      - web

networks:
    web:
      external: true