services:
  frontend:
    container_name: obsidian-theme
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    networks:
      - web

networks:
    web:
      external: true