services:
  app-dev:
    build:
      context: .
      target: development
    container_name: obsidian-theme-creator-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  app-prod:
    build:
      context: .
      target: production
    container_name: obsidian-theme-creator-prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
