import type { ThemeSection } from './sections';
import { deriveSection } from './derive';

/**
 * Generates the final CSS stylesheet for the theme, scoped under dark and/or light body classes.
 */
export function generateThemeCSS(
  sections: ThemeSection[],
  darkColors: Record<string, string>,
  lightColors: Record<string, string>,
  mode: 'dark' | 'light' | 'both',
  themeName: string
): string {
  const name = themeName.trim() || 'Untitled Theme';
  let css = `/* ${name} — generated by Obsidian Theme Creator */\n\n`;

  const generateBlock = (targetMode: 'dark' | 'light') => {
    let block = `body.theme-${targetMode} {\n`;
    const targetColors = targetMode === 'dark' ? darkColors : lightColors;
    for (const section of sections) {
      const hex = targetColors[section.id] || (targetMode === 'dark' ? section.defaultDark : section.defaultLight);
      const derived = deriveSection(section.id, hex);
      for (const [key, val] of Object.entries(derived)) {
        block += `  ${key}: ${val};\n`;
      }
    }
    block += `}\n`;
    return block;
  };

  if (mode === 'dark' || mode === 'both') {
    css += generateBlock('dark');
    if (mode === 'both') {
      css += '\n';
    }
  }
  if (mode === 'light' || mode === 'both') {
    css += generateBlock('light');
  }

  return css;
}
